namespace WebCronW10
{
    partial class FormWebCronMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.panelTop = new System.Windows.Forms.Panel();
            this.panelTopBorder = new System.Windows.Forms.Panel();
            this.panelTopContent = new System.Windows.Forms.Panel();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.panelBottom = new System.Windows.Forms.Panel();
            this.panelBottomBorder = new System.Windows.Forms.Panel();
            this.panelBottomContent = new System.Windows.Forms.Panel();
            this.panelLeft = new System.Windows.Forms.Panel();
            this.panelLeftBorder = new System.Windows.Forms.Panel();
            this.panelLeftContent = new System.Windows.Forms.Panel();
            this.labelCronJobs = new System.Windows.Forms.Label();
            this.panelRight = new System.Windows.Forms.Panel();
            this.panelRightBorder = new System.Windows.Forms.Panel();
            this.panelRightcontent = new System.Windows.Forms.Panel();
            this.labelScheduler = new System.Windows.Forms.Label();
            this.panelCenter = new System.Windows.Forms.Panel();
            this.panelCenterBorder = new System.Windows.Forms.Panel();
            this.panelCenterContent = new System.Windows.Forms.Panel();
            this.splitContainerCenter = new System.Windows.Forms.SplitContainer();
            this.panel1 = new System.Windows.Forms.Panel();
            this.labelBrowser = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.labelAutoGeneratedScript = new System.Windows.Forms.Label();
            this.webBrowserWebCron = new System.Windows.Forms.WebBrowser();
            this.panelCenterScriptTextbox = new System.Windows.Forms.Panel();
            this.textBoxWebCronScript = new System.Windows.Forms.TextBox();
            this.panelTop.SuspendLayout();
            this.panelTopBorder.SuspendLayout();
            this.panelTopContent.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.panelBottom.SuspendLayout();
            this.panelBottomBorder.SuspendLayout();
            this.panelLeft.SuspendLayout();
            this.panelLeftBorder.SuspendLayout();
            this.panelLeftContent.SuspendLayout();
            this.panelRight.SuspendLayout();
            this.panelRightBorder.SuspendLayout();
            this.panelRightcontent.SuspendLayout();
            this.panelCenter.SuspendLayout();
            this.panelCenterBorder.SuspendLayout();
            this.panelCenterContent.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerCenter)).BeginInit();
            this.splitContainerCenter.Panel1.SuspendLayout();
            this.splitContainerCenter.Panel2.SuspendLayout();
            this.splitContainerCenter.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panelCenterScriptTextbox.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelTop
            // 
            this.panelTop.Controls.Add(this.panelTopBorder);
            this.panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Location = new System.Drawing.Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new System.Drawing.Size(1266, 30);
            this.panelTop.TabIndex = 0;
            // 
            // panelTopBorder
            // 
            this.panelTopBorder.Controls.Add(this.panelTopContent);
            this.panelTopBorder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelTopBorder.Location = new System.Drawing.Point(0, 0);
            this.panelTopBorder.Name = "panelTopBorder";
            this.panelTopBorder.Size = new System.Drawing.Size(1266, 30);
            this.panelTopBorder.TabIndex = 0;
            // 
            // panelTopContent
            // 
            this.panelTopContent.Controls.Add(this.menuStrip1);
            this.panelTopContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelTopContent.Location = new System.Drawing.Point(0, 0);
            this.panelTopContent.Name = "panelTopContent";
            this.panelTopContent.Size = new System.Drawing.Size(1266, 30);
            this.panelTopContent.TabIndex = 0;
            // 
            // menuStrip1
            // 
            this.menuStrip1.BackColor = System.Drawing.Color.Transparent;
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1266, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStripMain";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(93, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(107, 22);
            this.aboutToolStripMenuItem.Text = "About";
            // 
            // panelBottom
            // 
            this.panelBottom.Controls.Add(this.panelBottomBorder);
            this.panelBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBottom.Location = new System.Drawing.Point(0, 580);
            this.panelBottom.Name = "panelBottom";
            this.panelBottom.Padding = new System.Windows.Forms.Padding(0, 5, 0, 0);
            this.panelBottom.Size = new System.Drawing.Size(1266, 30);
            this.panelBottom.TabIndex = 1;
            // 
            // panelBottomBorder
            // 
            this.panelBottomBorder.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.panelBottomBorder.Controls.Add(this.panelBottomContent);
            this.panelBottomBorder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBottomBorder.Location = new System.Drawing.Point(0, 5);
            this.panelBottomBorder.Name = "panelBottomBorder";
            this.panelBottomBorder.Size = new System.Drawing.Size(1266, 25);
            this.panelBottomBorder.TabIndex = 0;
            // 
            // panelBottomContent
            // 
            this.panelBottomContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBottomContent.Location = new System.Drawing.Point(0, 0);
            this.panelBottomContent.Name = "panelBottomContent";
            this.panelBottomContent.Size = new System.Drawing.Size(1266, 25);
            this.panelBottomContent.TabIndex = 0;
            // 
            // panelLeft
            // 
            this.panelLeft.Controls.Add(this.panelLeftBorder);
            this.panelLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelLeft.Location = new System.Drawing.Point(0, 30);
            this.panelLeft.Name = "panelLeft";
            this.panelLeft.Padding = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.panelLeft.Size = new System.Drawing.Size(300, 550);
            this.panelLeft.TabIndex = 2;
            // 
            // panelLeftBorder
            // 
            this.panelLeftBorder.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.panelLeftBorder.Controls.Add(this.panelLeftContent);
            this.panelLeftBorder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelLeftBorder.Location = new System.Drawing.Point(5, 0);
            this.panelLeftBorder.Name = "panelLeftBorder";
            this.panelLeftBorder.Padding = new System.Windows.Forms.Padding(1);
            this.panelLeftBorder.Size = new System.Drawing.Size(290, 550);
            this.panelLeftBorder.TabIndex = 0;
            // 
            // panelLeftContent
            // 
            this.panelLeftContent.BackColor = System.Drawing.Color.White;
            this.panelLeftContent.Controls.Add(this.labelCronJobs);
            this.panelLeftContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelLeftContent.Location = new System.Drawing.Point(1, 1);
            this.panelLeftContent.Name = "panelLeftContent";
            this.panelLeftContent.Size = new System.Drawing.Size(288, 548);
            this.panelLeftContent.TabIndex = 0;
            // 
            // labelCronJobs
            // 
            this.labelCronJobs.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.labelCronJobs.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelCronJobs.Location = new System.Drawing.Point(0, 0);
            this.labelCronJobs.Name = "labelCronJobs";
            this.labelCronJobs.Padding = new System.Windows.Forms.Padding(5);
            this.labelCronJobs.Size = new System.Drawing.Size(288, 23);
            this.labelCronJobs.TabIndex = 0;
            this.labelCronJobs.Text = "Cron Jobs";
            // 
            // panelRight
            // 
            this.panelRight.BackColor = System.Drawing.Color.Transparent;
            this.panelRight.Controls.Add(this.panelRightBorder);
            this.panelRight.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelRight.Location = new System.Drawing.Point(966, 30);
            this.panelRight.Name = "panelRight";
            this.panelRight.Padding = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.panelRight.Size = new System.Drawing.Size(300, 550);
            this.panelRight.TabIndex = 3;
            // 
            // panelRightBorder
            // 
            this.panelRightBorder.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.panelRightBorder.Controls.Add(this.panelRightcontent);
            this.panelRightBorder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRightBorder.Location = new System.Drawing.Point(5, 0);
            this.panelRightBorder.Margin = new System.Windows.Forms.Padding(10);
            this.panelRightBorder.Name = "panelRightBorder";
            this.panelRightBorder.Padding = new System.Windows.Forms.Padding(1);
            this.panelRightBorder.Size = new System.Drawing.Size(290, 550);
            this.panelRightBorder.TabIndex = 0;
            // 
            // panelRightcontent
            // 
            this.panelRightcontent.BackColor = System.Drawing.Color.White;
            this.panelRightcontent.Controls.Add(this.labelScheduler);
            this.panelRightcontent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRightcontent.Location = new System.Drawing.Point(1, 1);
            this.panelRightcontent.Name = "panelRightcontent";
            this.panelRightcontent.Size = new System.Drawing.Size(288, 548);
            this.panelRightcontent.TabIndex = 0;
            // 
            // labelScheduler
            // 
            this.labelScheduler.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.labelScheduler.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelScheduler.Location = new System.Drawing.Point(0, 0);
            this.labelScheduler.Name = "labelScheduler";
            this.labelScheduler.Padding = new System.Windows.Forms.Padding(5);
            this.labelScheduler.Size = new System.Drawing.Size(288, 23);
            this.labelScheduler.TabIndex = 0;
            this.labelScheduler.Text = "Scheduler";
            // 
            // panelCenter
            // 
            this.panelCenter.Controls.Add(this.panelCenterBorder);
            this.panelCenter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenter.Location = new System.Drawing.Point(300, 30);
            this.panelCenter.Name = "panelCenter";
            this.panelCenter.Size = new System.Drawing.Size(666, 550);
            this.panelCenter.TabIndex = 4;
            // 
            // panelCenterBorder
            // 
            this.panelCenterBorder.BackColor = System.Drawing.Color.Transparent;
            this.panelCenterBorder.Controls.Add(this.panelCenterContent);
            this.panelCenterBorder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenterBorder.Location = new System.Drawing.Point(0, 0);
            this.panelCenterBorder.Name = "panelCenterBorder";
            this.panelCenterBorder.Size = new System.Drawing.Size(666, 550);
            this.panelCenterBorder.TabIndex = 0;
            // 
            // panelCenterContent
            // 
            this.panelCenterContent.BackColor = System.Drawing.Color.White;
            this.panelCenterContent.Controls.Add(this.splitContainerCenter);
            this.panelCenterContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenterContent.Location = new System.Drawing.Point(0, 0);
            this.panelCenterContent.Name = "panelCenterContent";
            this.panelCenterContent.Size = new System.Drawing.Size(666, 550);
            this.panelCenterContent.TabIndex = 0;
            // 
            // splitContainerCenter
            // 
            this.splitContainerCenter.BackColor = System.Drawing.Color.White;
            this.splitContainerCenter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerCenter.Location = new System.Drawing.Point(0, 0);
            this.splitContainerCenter.Name = "splitContainerCenter";
            this.splitContainerCenter.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainerCenter.Panel1
            // 
            this.splitContainerCenter.Panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.splitContainerCenter.Panel1.Controls.Add(this.panel1);
            this.splitContainerCenter.Panel1.Padding = new System.Windows.Forms.Padding(1);
            // 
            // splitContainerCenter.Panel2
            // 
            this.splitContainerCenter.Panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.splitContainerCenter.Panel2.Controls.Add(this.panel2);
            this.splitContainerCenter.Panel2.Padding = new System.Windows.Forms.Padding(1);
            this.splitContainerCenter.Size = new System.Drawing.Size(666, 550);
            this.splitContainerCenter.SplitterDistance = 265;
            this.splitContainerCenter.SplitterWidth = 5;
            this.splitContainerCenter.TabIndex = 1;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.webBrowserWebCron);
            this.panel1.Controls.Add(this.labelBrowser);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(1, 1);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(664, 263);
            this.panel1.TabIndex = 0;
            // 
            // labelBrowser
            // 
            this.labelBrowser.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.labelBrowser.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelBrowser.Location = new System.Drawing.Point(0, 0);
            this.labelBrowser.Name = "labelBrowser";
            this.labelBrowser.Padding = new System.Windows.Forms.Padding(5);
            this.labelBrowser.Size = new System.Drawing.Size(664, 23);
            this.labelBrowser.TabIndex = 0;
            this.labelBrowser.Text = "Browser";
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Controls.Add(this.panelCenterScriptTextbox);
            this.panel2.Controls.Add(this.labelAutoGeneratedScript);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(1, 1);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(664, 278);
            this.panel2.TabIndex = 1;
            // 
            // labelAutoGeneratedScript
            // 
            this.labelAutoGeneratedScript.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.labelAutoGeneratedScript.Dock = System.Windows.Forms.DockStyle.Top;
            this.labelAutoGeneratedScript.Location = new System.Drawing.Point(0, 0);
            this.labelAutoGeneratedScript.Name = "labelAutoGeneratedScript";
            this.labelAutoGeneratedScript.Padding = new System.Windows.Forms.Padding(5);
            this.labelAutoGeneratedScript.Size = new System.Drawing.Size(664, 23);
            this.labelAutoGeneratedScript.TabIndex = 0;
            this.labelAutoGeneratedScript.Text = "Auto Generated Script";
            // 
            // webBrowserWebCron
            // 
            this.webBrowserWebCron.Dock = System.Windows.Forms.DockStyle.Fill;
            this.webBrowserWebCron.Location = new System.Drawing.Point(0, 23);
            this.webBrowserWebCron.MinimumSize = new System.Drawing.Size(20, 20);
            this.webBrowserWebCron.Name = "webBrowserWebCron";
            this.webBrowserWebCron.Size = new System.Drawing.Size(664, 240);
            this.webBrowserWebCron.TabIndex = 1;
            // 
            // panelCenterScriptTextbox
            // 
            this.panelCenterScriptTextbox.Controls.Add(this.textBoxWebCronScript);
            this.panelCenterScriptTextbox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenterScriptTextbox.Location = new System.Drawing.Point(0, 23);
            this.panelCenterScriptTextbox.Name = "panelCenterScriptTextbox";
            this.panelCenterScriptTextbox.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.panelCenterScriptTextbox.Size = new System.Drawing.Size(664, 255);
            this.panelCenterScriptTextbox.TabIndex = 2;
            // 
            // textBoxWebCronScript
            // 
            this.textBoxWebCronScript.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBoxWebCronScript.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxWebCronScript.Location = new System.Drawing.Point(10, 0);
            this.textBoxWebCronScript.Multiline = true;
            this.textBoxWebCronScript.Name = "textBoxWebCronScript";
            this.textBoxWebCronScript.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textBoxWebCronScript.Size = new System.Drawing.Size(654, 255);
            this.textBoxWebCronScript.TabIndex = 2;
            this.textBoxWebCronScript.Text = "As you navigate within the browser above, script is automatically generated. If a" +
    "ction supports variations that can be repeated, options are presented.";
            // 
            // FormWebCronMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1266, 610);
            this.Controls.Add(this.panelCenter);
            this.Controls.Add(this.panelRight);
            this.Controls.Add(this.panelLeft);
            this.Controls.Add(this.panelBottom);
            this.Controls.Add(this.panelTop);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "FormWebCronMain";
            this.Text = "Web Cron for Windows 10";
            this.panelTop.ResumeLayout(false);
            this.panelTopBorder.ResumeLayout(false);
            this.panelTopContent.ResumeLayout(false);
            this.panelTopContent.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.panelBottom.ResumeLayout(false);
            this.panelBottomBorder.ResumeLayout(false);
            this.panelLeft.ResumeLayout(false);
            this.panelLeftBorder.ResumeLayout(false);
            this.panelLeftContent.ResumeLayout(false);
            this.panelRight.ResumeLayout(false);
            this.panelRightBorder.ResumeLayout(false);
            this.panelRightcontent.ResumeLayout(false);
            this.panelCenter.ResumeLayout(false);
            this.panelCenterBorder.ResumeLayout(false);
            this.panelCenterContent.ResumeLayout(false);
            this.splitContainerCenter.Panel1.ResumeLayout(false);
            this.splitContainerCenter.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerCenter)).EndInit();
            this.splitContainerCenter.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panelCenterScriptTextbox.ResumeLayout(false);
            this.panelCenterScriptTextbox.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelTop;
        private System.Windows.Forms.Panel panelBottom;
        private System.Windows.Forms.Panel panelLeft;
        private System.Windows.Forms.Panel panelRight;
        private System.Windows.Forms.Panel panelCenter;
        private System.Windows.Forms.Panel panelTopBorder;
        private System.Windows.Forms.Panel panelBottomBorder;
        private System.Windows.Forms.Panel panelLeftBorder;
        private System.Windows.Forms.Panel panelRightBorder;
        private System.Windows.Forms.Panel panelCenterBorder;
        private System.Windows.Forms.Panel panelRightcontent;
        private System.Windows.Forms.Panel panelTopContent;
        private System.Windows.Forms.Panel panelBottomContent;
        private System.Windows.Forms.Panel panelLeftContent;
        private System.Windows.Forms.Panel panelCenterContent;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.Label labelCronJobs;
        private System.Windows.Forms.Label labelScheduler;
        private System.Windows.Forms.Label labelBrowser;
        private System.Windows.Forms.SplitContainer splitContainerCenter;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label labelAutoGeneratedScript;
        private System.Windows.Forms.WebBrowser webBrowserWebCron;
        private System.Windows.Forms.Panel panelCenterScriptTextbox;
        private System.Windows.Forms.TextBox textBoxWebCronScript;
    }
}

